global:
  scrape_interval:     10s
  evaluation_interval: 5s

rule_files:
  - "/etc/prometheus/targets/targets.rules"

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module:
        - http_2xx  # Look for a HTTP 200 response.
        - icmp
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets:
###############################################################################
# local
###############################################################################
###############################################################################
# services
###############################################################################
        - https://ya.ru
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'node_exporter'
    scrape_interval: 30s
    scheme: http
    metrics_path: /metrics
    static_configs:
     - targets:
       - node_exporter:9100
       labels:
         environment: local
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
      - source_labels: [__param_target]
        target_label: instance


  - job_name: 'cadvisor'
    scrape_interval: 30s
    scheme: http
    metrics_path: /metrics
    static_configs:
     - targets:
         - cadvisor:8080
       labels:
         environment: local
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
      - source_labels: [__param_target]
        target_label: instance

